fibresInTexilesMvc/fibresInTexilesMvc/ViewModels/FibAndProdViewModel.cs
using fibresInTexilesMvc.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace fibresInTexilesMvc.ViewModels
{
    public class FibAndProdViewModel

    {
        public int FiberId { get; set; }
        public string Picture1 { get; set; }
        public string Description { get; set; }
        public string Advantages { get; set; }
        public string Disadvantages { get; set; }
        public string Picture2 { get; set; }

        public string Picture { get; set; }
        public string Name { get; set; }
       
        public virtual ICollection<product> Products { get; set; }
      
        public virtual fibre fibre { get; set; }
    }
}

fibresInTexilesMvc/fibresInTexilesMvc/Controllers/FibAndProdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using fibresInTexilesMvc.Models;
using fibresInTexilesMvc.ViewModels;
using System.Net;

namespace fibresInTexilesMvc.Controllers
{
    public class FibAndProdController : Controller
    {
        private fibresInTextilesEntities db = new fibresInTextilesEntities();
        
        public ActionResult Index()
        {
            return View();
        }

        // GET: FibAndProd
        public ActionResult DetailsVM(int? FiberId)
        {
            if (FiberId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FibAndProdViewModel fibprodVm = new FibAndProdViewModel();
            fibprodVm.fibre = (from f in db.fibres
                               where f.FiberId == FiberId
                               select f).FirstOrDefault();
            fibprodVm.Products = (from p in db.products
                                  where p.FiberId == FiberId
                                  select p).ToList();

            if (fibprodVm == null)
            {
                return HttpNotFound();
            }
            return View(fibprodVm);
        }
       
    }
}

fibresInTexilesMvc/fibresInTexilesMvc/Controllers/productsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using fibresInTexilesMvc.Models;
using fibresInTexilesMvc.ViewModels;

namespace fibresInTexilesMvc.Controllers
{
    public class productsController : Controller
    {
        private fibresInTextilesEntities db = new fibresInTextilesEntities();

        // GET: products
        public ActionResult Index(int?FiberId)
        {
            var products = db.products.Include(p => p.fibre);
            return View(products.ToList());
        }
        public ActionResult GetProducts(int? FiberId)
        {
            var prod = from p in db.products
                         where p.FiberId == FiberId
                         select p;
          
            return View(prod);
        }

        // GET: products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: products/Create
        public ActionResult Create()
        {
            ViewBag.FiberId = new SelectList(db.fibres, "FiberId", "Name");
            return View();
        }

        // POST: products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,Name,Picture,Overview,FiberId")] product product)
        {
            if (ModelState.IsValid)
            {
                db.products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FiberId = new SelectList(db.fibres, "FiberId", "Name", product.FiberId);
            return View(product);
        }

        // GET: products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.FiberId = new SelectList(db.fibres, "FiberId", "Name", product.FiberId);
            return View(product);
        }

        // POST: products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,Name,Picture,Overview,FiberId")] product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FiberId = new SelectList(db.fibres, "FiberId", "Name", product.FiberId);
            return View(product);
        }

        // GET: products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            product product = db.products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            product product = db.products.Find(id);
            db.products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

fibresInTexilesMvc/fibresInTexilesMvc/Views/FibAndProd/Details.cshtml
@model fibresInTexilesMvc.ViewModels.FibAndProdViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>FibAndProdViewModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FiberId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FiberId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Picture1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Picture1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Advantages)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Advantages)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Disadvantages)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Disadvantages)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Picture2)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Picture2)
            </dd>
    
            <dt>
                @*<img src="@Url.Content(@Model.Picture2)" />*@
                @Html.DisplayNameFor(model => model.Picture)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Picture)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

fibresInTexilesMvc/fibresInTexilesMvc/Views/FibAndProd/DetailsVM.cshtml
@model fibresInTexilesMvc.ViewModels.FibAndProdViewModel

@*@model <fibresInTexilesMvc.ViewModels.DetailsVM>*@
@{

    ViewBag.Title = "DetailsVM";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Content/myCSS.css" rel="stylesheet" />
    <script src="~/Content/JavaScript.js"></script>
    <link href="~/Content/myCSS.css" rel="stylesheet" />
    <!--specific fonts-->
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <title>DetailsVM</title>
</head>
<body>
    <style>
      #prod{
          margin-bottom:5em;
      }
      .pageHeader{
    padding-bottom: 10px;
    margin: 25px 14px 37px;
    border-bottom: 1px solid #eee;

}
#productList h3{
    font-size: 27px;
    margin-top: 4em;
    margin-bottom: 10px;
}
.page-header{
        padding-bottom: 9px;
    margin: 6em 0 5em;
    border-bottom: 1px solid #c1bdbe;
}

    </style>
    @*<div >*@ 
        
        @*<table>*@ 
        <div class="container" id="details-VM">
                <div class="row-DetailsVM">
                                     
                        <div class="col-xs-12 col-md-4 col-sm-6" id="imgCont1">
                            <div class="imageCont1">
                                <img src="@Url.Content(Model.fibre.Picture1)" class="img-responsive" width="390" height="390"/>
                            </div>
                        </div>

                        <div class="col-xs-12 col-md-4 col-sm-6 fibContMiddleColumn"  @*id="fibCont"*@>
                            <div class="fibCont" >
                                <p2>@*<h2>*@<p1>@Html.DisplayFor(model => Model.fibre.Name)</p1>@*<span> ...</span></h2><span>...</span>*@<p4> @Html.DisplayFor(model => Model.fibre.Description)</p4></p2>
                                <h5><strong>@Html.DisplayNameFor(model => Model.fibre.Advantages)</strong></h5>
                                <p4>@Html.DisplayFor(model => Model.fibre.Advantages)</p4>
                                <h5><strong>@Html.DisplayNameFor(model => Model.fibre.Disadvantages)</strong></h5>
                                <p4>@Html.DisplayFor(model => Model.fibre.Disadvantages)</p4>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-4 col-sm-6" id="imgCont2" style="padding-left:12px;">
                            <div class="imageCont2">
                                <img src="@Url.Content(Model.fibre.Picture2)" class="img-responsive" width="390" height="390" />
                            </div>
                        </div>             
                    </div>                  
        </div>
    @*</table>*@
              
              @*<hr/>*@
                @*<h3>Products</h3>*@
        
      
        <div class="container">
            <div class="page-header" id="productsList"><h3>Products</h3></div>
           
            @*<div class="row-fluid" id="rowProductsList">*@
                <div class="row" id="prod">
                    @*<div  class="col-xs-6  col-md-2 col-sm-6"></div>*@
                    @foreach (var products in Model.Products)
                    {

                        <div class="col-xs-6  col-md-3 col-sm-6 col-lg-offset-1 ">
                            <a href="@Url.Action("Details","products", new { id = products.ProductId })">
                                <img src="@Url.Content(products.Picture)" class="img-responsive" />
                            </a>
                            <div class="text-center" id="productName">
                                @Html.DisplayName(products.Name)
                            </div>
                        </div>
                    }
                </div>

                @*</div>*@
            </div>
        @*</div>*@
</body>
</html>

fibresInTexilesMvc/fibresInTexilesMvc/Views/FibAndProd/FibAndProdVm.cshtml
@model IEnumerable<fibresInTexilesMvc.ViewModels.FibAndProdViewModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>FibAndProdVm</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FiberId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Advantages)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Disadvantages)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FiberId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Picture1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Advantages)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disadvantages)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Picture2)
            </td>
            <td>
                <img src="@Url.Content(item.Picture)" />
                @*@Html.DisplayFor(modelItem => item.Picture)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>