fibresInTexilesMvc/fibresInTexilesMvc/Controllers/FibAndProdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using fibresInTexilesMvc.Models;
using fibresInTexilesMvc.ViewModels;
using System.Net;

namespace fibresInTexilesMvc.Controllers
{
    public class FibAndProdController : Controller
    {
        private fibresInTextilesEntities db = new fibresInTextilesEntities();
        
        public ActionResult Index()
        {
            return View();
        }

        // GET: FibAndProd
        public ActionResult DetailsVM(int? FiberId)
        {
            if (FiberId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FibAndProdViewModel fibprodVm = new FibAndProdViewModel();
            fibprodVm.fibre = (from f in db.fibres
                               where f.FiberId == FiberId
                               select f).FirstOrDefault();
            fibprodVm.Products = (from p in db.products
                                  where p.FiberId == FiberId
                                  select p).ToList();

            if (fibprodVm == null)
            {
                return HttpNotFound();
            }
            return View(fibprodVm);
        }
       
    }
}

fibresInTexilesMvc/fibresInTexilesMvc/Controllers/HomeController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using fibresInTexilesMvc.Models;
using fibresInTexilesMvc.ViewModels;

namespace fibresInTexilesMvc.Controllers
{
    public class HomeController : Controller
    {
      
        private fibresInTextilesEntities db = new fibresInTextilesEntities();
                    
        // GET: Home
        public ActionResult Index(int?FiberId)

        {
            var fibres = db.fibres.Include(f => f.products);
            return View(db.fibres);
        }
   
    // GET: Home/Details/5
    public ActionResult Details(int?id)

        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            fibre fibre = db.fibres.Find(id);

            if (fibre == null)
            {
                return HttpNotFound();
            }             
            return View(fibre);        
    }
    // GET: Home/Create
    public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FiberId,Name,Category,Picture1,Description,Advantages,Disadvantages,Picture2")] fibre fibre)
        {
            if (ModelState.IsValid)
            {
                db.fibres.Add(fibre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fibre);
        }

        // GET: Home/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            fibre fibre = db.fibres.Find(id);
            if (fibre == null)
            {
                return HttpNotFound();
            }
            return View(fibre);
        }

        // POST: Home/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FiberId,Name,Category,Picture1,Description,Advantages,Disadvantages,Picture2")] fibre fibre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fibre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fibre);
        }

        // GET: Home/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            fibre fibre = db.fibres.Find(id);
            if (fibre == null)
            {
                return HttpNotFound();
            }
            return View(fibre);
        }

        // POST: Home/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            fibre fibre = db.fibres.Find(id);
            db.fibres.Remove(fibre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

fibresInTexilesMvc/fibresInTexilesMvc/Views/Home/Cotton.cshtml
@model IEnumerable<fibresInTexilesMvc.Models.product>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cotton</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Overview)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fibre.Name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Picture)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Overview)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fibre.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ProductId }) |
                @Html.ActionLink("Details", "Details", new { id=item.ProductId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ProductId })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

fibresInTexilesMvc/fibresInTexilesMvc/Views/Home/Create.cshtml
@model fibresInTexilesMvc.Models.fibre

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>fibre</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Picture1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Picture1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Picture1, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Advantages, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Advantages, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Advantages, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Disadvantages, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Disadvantages, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Disadvantages, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Picture2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Picture2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Picture2, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

fibresInTexilesMvc/fibresInTexilesMvc/Views/Home/Delete.cshtml
@model fibresInTexilesMvc.Models.fibre

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>fibre</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Category)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Picture1)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Picture1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Advantages)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Advantages)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Disadvantages)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Disadvantages)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Picture2)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Picture2)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

fibresInTexilesMvc/fibresInTexilesMvc/Views/Home/Details.cshtml
@model fibresInTexilesMvc.Models.fibre

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>fibre</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FiberId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FiberId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Category)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Category)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Picture1)
            </dt>
    
            <dd>
                @Html.Image(@Model.Picture1)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Advantages)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Advantages)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Disadvantages)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Disadvantages)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Picture2)
            </dt>
    
            <dd>
                @Html.Image(Model.Picture2)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

fibresInTexilesMvc/fibresInTexilesMvc/Views/Home/Edit.cshtml
@model fibresInTexilesMvc.Models.fibre

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>fibre</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.FiberId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Picture1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Picture1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Picture1, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Advantages, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Advantages, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Advantages, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Disadvantages, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Disadvantages, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Disadvantages, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Picture2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Picture2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Picture2, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

fibresInTexilesMvc/fibresInTexilesMvc/Views/Home/GetFiberProd.cshtml
@model fibresInTexilesMvc.ViewModels.FibAndProdViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetFiberProd</title>
</head>
<body>
    <table>
        <tr>
            <td>
                @Html.DisplayFor(f => f.fibre.Picture1)
        </td>
            <td>
                @Html.DisplayFor(f=>f.fibre.Description)
            </td>
            <td>
                @Html.DisplayFor(f=>f.fibre.Picture2)
            </td>
    </tr>
    </table>
    <h3>Products</h3>
    <table>
        @foreach(var product in Model.Products)
        {
            <tr>
                <td>
                    @*@Html.Image(@Model.Picture)*@
                    @product.Picture
                </td>
                <td>
                    @product.Name
                </td>
            </tr>
        }
    </table>
    @*<div> 
    </div>*@
</body>
</html>

fibresInTexilesMvc/fibresInTexilesMvc/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="~/Content/myCSS.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body>
    @{
        ViewBag.Title = "Index";
    }
    <style>

        *{
            margin:0px;
            padding:0px;
        }
        /** {
            margin: 0px;
            padding: 0px;
            color: red;
            text-transform: uppercase;
            font-size: 4vw;
            font-weight: bold;
            line-height: 1.8em;
            letter-spacing: 5px;
        }*/
        
        html,body{
            background-color:transparent;
            margin:0;          
        }
        
        #rowLinks{
            margin-top:9%;            
        }

        html {
            background: url('../Content/imgLandingPage/men1-second-upSpace-third.jpg') no-repeat center top fixed;      
            background-size: cover;                  
        } 
        #rowLinks > ul > li{list-style:none;
                            text-decoration:none;
        }
            /*a{ color: #eaa87f;
    text-decoration: none;
    line-height: 1.4;
    font-size: 2em;
}*/
        .list-unstyled{
            color:#efb74c;
            
            text-transform:uppercase;
        } 
        .list-unstyled li:first-child{
            font-size: 1.8em;
            font-weight: 700;
            line-height: 1.8em;
            letter-spacing:0.4em;
            font-weight:800;
        }
        .list-unstyled a{
            color:#fcfef1;
            font-size: 1.8em;
            font-weight: 700;
            line-height: 1.8em;
            letter-spacing:0.4em;
            text-decoration:none;
        }
         .list-unstyled a:hover{
             color:#fbe3b5;
         }
        
    </style>
   
    <div class="bg">
    <div class="container body-content" id="landingPage">      
    <div class="row" id="rowLinks">              
                    <div class="col-lg-3  col-sm-12 col-md-4"> 
                        <ul class="text-center list-unstyled" id="links">                           
                                <li>
                                    NATURAL
                                    @*<a href="/natural/" class="banner-nav__heading">NATURAL</a>*@
                                </li>
                                <li>
                                    @Html.ActionLink("Cotton", "DetailsVM", "FibAndProd", new { FiberId = "1" }, null)
                                </li>
                                <li>@Html.ActionLink("Wool", "DetailsVM", "FibAndProd", new { FiberId = "2" }, null)</li>
                                <li>@Html.ActionLink("Silk", "DetailsVM", "FibAndProd", new { FiberId = "3" }, null)</li>
                                <li>@Html.ActionLink("Flax", "DetailsVM", "FibAndProd", new { FiberId = "4" }, null)</li>
                                <li>@Html.ActionLink("Hemp", "DetailsVM", "FibAndProd", new { FiberId = "5" }, null)</li>
                                <li>@Html.ActionLink("Jute", "DetailsVM", "FibAndProd", new { FiberId = "6" }, null)</li>                           
                        </ul>
                    </div>
                @*<div class="banner-nav banner-nav__split-expanded">*@
                    <div class="col-lg-4 col-lg-offset-5 col-sm-12 col-md-4 col-md-offset-4">
                        @*<div class="col-md-6">*@
                        @*<div class="syntheticFibresSection">*@
                        <ul class="text-center list-unstyled" id="links">
                            <li>SYNTHETIC</li>

                            <li>@Html.ActionLink("Polyester", "DetailsVM", "FibAndProd", new { FiberId = "8" }, null)</li>
                            <li>@Html.ActionLink("Acrylic", "DetailsVM", "FibAndProd", new { FiberId = "9" }, null)</li>
                            <li>@Html.ActionLink("Nylon", "DetailsVM", "FibAndProd", new { FiberId = "10" }, null)</li>
                            <li>@Html.ActionLink("Spandex", "DetailsVM", "FibAndProd", new { FiberId = "11" }, null)</li>
                            <li>@Html.ActionLink("Kevlar", "DetailsVM", "FibAndProd", new { FiberId = "12" }, null)</li>
                            @*</div>*@
                            @*</div>*@
                        </ul>
                    </div>
                @*</div>*@
          
        @*</div>*@
    </div>
    </div>
    </div>

</body>
</html>